[package]
name        = "flo_scene"
version     = "0.1.0"
edition     = "2021"
authors     = ["Andrew Hunter"]
license     = "Apache-2.0"
readme      = "README.md"
repository  = "https://github.com/Logicalshift/flo_scene"
description = "Entity-messaging system for composing large programs from small programs"
categories  = [ "concurrency", "data-structures" ]
keywords    = [ "message-queue" ]
resolver    = "2"

[features]
test-scene      = [ "futures-timer" ]

[dependencies]
futures         = "0.3"
uuid            = { version = "1.0", features = [ "v4" ] }
desync          = "0.7"
futures-timer   = { version = "3.0", optional = true }

[dev-dependencies]
flo_scene       = { path = ".", features = ["test-scene"] }

[patch.crates-io]
desync                  = { git = "https://github.com/Logicalshift/desync", branch = "v0.7.0" }
