[package]
name        = "flo_scene"
version     = "0.1.0"
edition     = "2021"
authors     = ["Andrew Hunter"]
license     = "Apache-2.0"
readme      = "README.md"
repository  = "https://github.com/Logicalshift/flo_scene"
description = "Entity-messaging system for composing large programs from small programs"
categories  = [ "concurrency", "data-structures" ]
keywords    = [ "message-queue" ]
resolver    = "2"

[features]
test-scene  = []

[dependencies]
futures     = "0.3"
uuid        = { version = "1.0", features = [ "v4" ] }
desync      = "0.7"

[dev-dependencies]
flo_scene   = { path = ".", features = ["test-scene"] }
